# This workflow will install Python 3, run readme_generator.py, save output to README.md and then push changes.

name: Update README.md

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Run readme_generator.py 
      run: |
        python3 readme_generator.py > README.md
        # python3 readme_generator.py
    - name: Commit Changes
      run: |
        git config --global user.name 'WindJammer6'
        git config --global user.email 'WindJammer6@users.noreply.github.com'
        git commit -am "Updated README.md"
        git push
